//! Per-application authenticated encryption.
//!
//! Every application (name + token, see main.rs) also supplies a
//! `secret` at registration: a random string chosen once, out of band, by
//! whoever pairs that application's devices (a QR code, manual entry,
//! whatever the application's own UX wants — syncd is never involved in
//! establishing it, only in using it). Two ends that know the same secret
//! can talk; ones that don't, can't — even if they can reach the port.
//!
//! There is no PKI and no certificates here. `derive_key` turns the
//! secret into a symmetric key, and every request and response body for
//! that application — whether the caller is a local client talking to its
//! own syncd, or a peer syncd reconciling state over the network — is an
//! `Envelope`: sealed with ChaCha20-Poly1305 (AEAD), which gives both
//! confidentiality and, in the same step, integrity/authenticity. A
//! forged or tampered envelope simply fails to open; there's no separate
//! "signature" to check, because a successfully opened envelope already
//! proves the sender knew the key.

use base64::Engine;
use chacha20poly1305::{aead::Aead, ChaCha20Poly1305, KeyInit};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

pub type Key = [u8; 32];

/// Derives this application's symmetric key from its secret. Plain
/// SHA-256 rather than a slow KDF (Argon2/scrypt) is a deliberate choice:
/// the secret is expected to be a high-entropy random string generated by
/// a pairing flow, not a human-memorized password, so there's nothing for
/// a slow KDF to protect against that a fast hash doesn't already resist.
pub fn derive_key(secret: &str) -> Key {
    let mut hasher = Sha256::new();
    hasher.update(secret.as_bytes());
    hasher.finalize().into()
}

/// An encrypted request or response body. Wire-safe (both fields are
/// plain base64 strings), so it drops into any JSON body without special
/// handling on either end.
#[derive(Serialize, Deserialize)]
pub struct Envelope {
    /// base64-encoded 12-byte nonce, freshly random per message — AEAD
    /// requires a unique nonce per encryption under the same key, never
    /// reused.
    n: String,
    /// base64-encoded ciphertext (the Poly1305 authentication tag is
    /// appended to it by the `aead` crate, not stored separately).
    ct: String,
}

fn b64(bytes: &[u8]) -> String {
    base64::engine::general_purpose::STANDARD.encode(bytes)
}

fn unb64(s: &str) -> Option<Vec<u8>> {
    base64::engine::general_purpose::STANDARD.decode(s).ok()
}

/// Serializes `value` to JSON and seals it under `key`.
pub fn seal<T: Serialize>(key: &Key, value: &T) -> Envelope {
    let cipher = ChaCha20Poly1305::new(key.into());
    let mut nonce_bytes = [0u8; 12];
    getrandom::getrandom(&mut nonce_bytes).expect("OS RNG unavailable");
    let plaintext = serde_json::to_vec(value).expect("Envelope payload must serialize");
    let ct = cipher
        .encrypt(chacha20poly1305::Nonce::from_slice(&nonce_bytes), plaintext.as_ref())
        .expect("ChaCha20-Poly1305 encryption cannot fail for a valid key/nonce");
    Envelope { n: b64(&nonce_bytes), ct: b64(&ct) }
}

/// Opens `env` under `key` and deserializes the result. `None` covers
/// every failure mode uniformly (bad base64, wrong key, tampered
/// ciphertext, or a plaintext that isn't the expected JSON shape) — the
/// caller can't distinguish "wrong secret" from "malformed request" from
/// the outside anyway, so there's nothing useful a more specific error
/// would add, and not distinguishing them avoids leaking which part of a
/// forged request happened to be wrong.
pub fn open<T: for<'de> Deserialize<'de>>(key: &Key, env: &Envelope) -> Option<T> {
    let nonce_bytes = unb64(&env.n)?;
    if nonce_bytes.len() != 12 {
        return None;
    }
    let ct = unb64(&env.ct)?;
    let cipher = ChaCha20Poly1305::new(key.into());
    let plaintext = cipher.decrypt(chacha20poly1305::Nonce::from_slice(&nonce_bytes), ct.as_ref()).ok()?;
    serde_json::from_slice(&plaintext).ok()
}
